language: php
php:
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable16
    - APP_NAME=ransomware_detection
    - DB=sqlite

branches:
  only:
    - master
    - develop
    - /^feature.*$/

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - . ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../server
  - ./occ check
  - ./occ status
  - ./occ app:enable $APP_NAME
  - ./occ app:list

jobs:
  fast_finish: true
  allow_failures:
    - env: DB=mysql;CODECHECK=2
  include:
    - stage: test
      script: cd apps/$APP_NAME/

      # Test the app
      script: sh -c "if [ '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
      script: cd ../../
      script: sh -c "if [ '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
      script: sh -c "if [ '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
      script: cd apps/$APP_NAME/

      # Run phpunit tests
      script: sh -c "if [ '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then phpunit --configuration phpunit.xml; fi"
      php: 7.0
      env: "DB=sqlite CORE_BRANCH=stable13"
      php: 7.0
      env: "DB=sqlite CORE_BRANCH=stable14"
      php: 7.0
      env: "DB=sqlite CORE_BRANCH=stable15"
      php: 7.1
      env: DB=mysql
      php: 7.1
      env: DB=pgsql
      php: 7.1
      env: DB=mysql;CODECHECK=1
      php: 7.1
      env: DB=mysql;CODECHECK=2

after_success:
  # Create coverage report
  - cd tests
  - sh -c "if [ '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then wget https://codecov.io/bash -O codecov.sh; fi"
  - sh -c "if [ '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then bash codecov.sh; fi"
  - cd ..
