language: php

env:
  global:
    - CORE_BRANCH=stable16
    - APP_NAME=ransomware_detection

branches:
  only:
    - master
    - develop
    - /^feature.*$/

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - . ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server
  - ./occ check
  - ./occ status
  - ./occ app:enable $APP_NAME
  - ./occ app:list

jobs:
  fast_finish: true
  allow_failures:
    - env: "CHECKSTYLE=2"
  include:
    - stage: test
      php: 7.0
      env: 
        - DB=sqlite
        - CORE_BRANCH=stable13
      script: 
        - cd apps/$APP_NAME/
        - phpunit --configuration phpunit.xml
    - stage: test
      php: 7.0
      env: 
        - DB=sqlite
        - CORE_BRANCH=stable14
      script: 
        - cd apps/$APP_NAME/
        - phpunit --configuration phpunit.xml
    - stage: test
      php: 7.0
      env: 
        - DB=sqlite
        - CORE_BRANCH=stable15
      script: 
        - cd apps/$APP_NAME/
        - phpunit --configuration phpunit.xml
    - stage: test
      php: 7.1
      env: 
        - DB=mysql
      script: 
        - cd apps/$APP_NAME/
        - phpunit --configuration phpunit.xml
    - stage: test
      php: 7.1
      env: 
        - DB=pgsql
      script: 
        - cd apps/$APP_NAME/
        - phpunit --configuration phpunit.xml
    - stage: test
      php: 7.1
      env: 
        - DB=mysql
      script: 
        - cd apps/$APP_NAME/
        - phpunit --configuration phpunit.xml
    - stage: test
      php: 7.1
      env: 
        - DB=mysql
        - CHECKSTYLE=1
      script: 
        - ./occ app:check-code $APP_NAME -c private -c strong-comparison
    - stage: test
      php: 7.1
      env: 
        - DB=mysql
        - CHECKSTYLE=2
      script: 
        - ./occ app:check-code $APP_NAME -c deprecation
    - stage: build
      php: 7.1
      env: 
        - DB=sqlite
      script:
        - make appstore

stages:
  - test
  - build
  - name: deploy
    if: tag =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$

after_success:
  # Create coverage report
  - cd tests
  - sh -c "if [ '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then wget https://codecov.io/bash -O codecov.sh; fi"
  - sh -c "if [ '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then bash codecov.sh; fi"
  - cd ..
